"""Formatting helpers for news digests."""

from __future__ import annotations


def build_final_message(digest_body: str, date_iso: str) -> str:
    """Wrap digest body with standard header/footer."""
    return (
        f"🤖 **AI Daily Analyst** - {date_iso}\n\n"
        f"{digest_body}\n\n"
        "_Generated by Archon News Agent_"
    )


def truncate_for_telegram(text: str, limit: int = 4000) -> str:
    """Conservative message truncation helper."""
    if len(text) <= limit:
        return text
    return text[:limit] + "\n... (truncated)"


def chunk_for_telegram(text: str, limit: int = 4000) -> list[str]:
    """Split a long message into Telegram-safe chunks."""
    if len(text) <= limit:
        return [text]

    chunks: list[str] = []
    remaining = text
    while remaining:
        if len(remaining) <= limit:
            chunks.append(remaining)
            break
        split_at = remaining.rfind("\n", 0, limit)
        if split_at < 1:
            split_at = limit
        chunks.append(remaining[:split_at])
        remaining = remaining[split_at:].lstrip("\n")
    return chunks
